[package]
name = "cmdcreate"
authors = ["Owen Debiasio <owen.debiasio@gmail.com>"]
license = "GPL-2.0-only"
version = "1.0.3"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.21.3"
toml = "0.9.10"
chrono = "0.4.43"

[lints.rust]
unsafe_code = "forbid"
warnings = "warn"

[lints.clippy]
correctness = "deny"
suspicious = "deny"
perf = "warn"
complexity = "warn"
style = "warn"
pedantic = "warn"
nursery = "allow"
cargo = "allow"
restriction = "allow"
internal = "allow"
