[package]
name = "cmdcreate"
authors = ["Owen Debiasio <owen.debiasio@gmail.com>"]
license = "GPL-2.0-only"
version = "1.0.5"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9.10"
chrono = "0.4.43"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = "deny"
nursery = "deny"
perf = "deny"
complexity = "warn"
style = "warn"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
incremental = true
