[package]
name = "cmdcreate"
license = "MIT"
version = "1.0.8"
edition = "2024"
authors = ["Owen Debiasio <owen.debiasio@gmail.com>"]
repository = "https://github.com/owen-debiasio/cmdcreate"
description = "Create your own custom commands for your convenience without needing to enter the same \"complex\" commands over and over."
readme = "README.md"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9.10"
chrono = "0.4.43"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = "deny"
nursery = "deny"
perf = "deny"
complexity = "warn"
style = "warn"

[profile.release]
lto = true
codeBin-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
incremental = true
