[package]
name = "cmdcreate"
authors = ["Owen Debiasio <owen.debiasio@gmail.com>"]
license = "MIT"
version = "0.9.0"
edition = "2024"

[dependencies]
shellexpand = "3.1.1"
dirs = "6.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
whoami = "1.6.1"
once_cell = "1.21.3"
toml = "0.9.10"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = "deny"
nursery = "deny"
perf = "deny"
complexity = "warn"
style = "warn"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
incremental = true
