[package]
name = "cmdcreate"
license = "MIT"
version = "1.1.2"
edition = "2024"
authors = ["Owen Debiasio <owen.debiasio@gmail.com>"]
repository = "https://github.com/owen-debiasio/cmdcreate"
readme = "README.md"

[dependencies]
reqwest = { version = "0.12.28", features = ["blocking", "json"] }
serde_json = "1.0"
toml = "1.0.1"
chrono = "0.4.43"
rustix = { version = "0.38", features = ["process"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = "deny"
nursery = "deny"
perf = "deny"
complexity = "warn"
style = "warn"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
incremental = true
