[package]
name = "cmdcreate"
version = "0.8.6"
edition = "2024"

[dependencies]
shellexpand = "3.1.1"
dirs = "6.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
whoami = "1.6.1"
once_cell = "1.21.3"
alpm = "5.0.0"
ctrlc = "3.5.1"
