words = [
    "aur",
    "clippy",
    "cmdcreate",
    "cmdcreate's",
    "debiasio",
    "Debiasio",
    "dnf",
    "dominiquini",
    "dpkg",
    "favoriting",
    "kwrite",
    "linuxmint",
    "makepkg",
    "misdetection",
    "noconfirm",
    "openssl",
    "pacman",
    "paru",
    "reqwest",
    "rustup",
    "upgrader",
    "uvh",
    "vscodium",
    "yay",
]
