words = [
    "aur",
    "centos",
    "chmod",
    "clippy",
    "cmdcreate",
    "cmdcreate's",
    "codebook",
    "debiasio",
    "distros",
    "dnf",
    "dominiquini",
    "dpkg",
    "dtolnay",
    "Dwarnings",
    "Eeuo",
    "favorited",
    "favoriting",
    "gedit",
    "kwrite",
    "linuxmint",
    "listandfavorite",
    "lvl",
    "makepkg",
    "manjaro",
    "misdetection",
    "noconfirm",
    "nvim",
    "openssl",
    "pacman",
    "paru",
    "pkgdir",
    "pylint",
    "pylintrc",
    "reqwest",
    "rhel",
    "RUSTFLAGS",
    "rustup",
    "sarif",
    "shellcheck",
    "shfmt",
    "Swatinem",
    "tlsv",
    "upgrader",
    "uvh",
    "vscodium",
    "Vvcr",
    "yay"
]
