words = [
    "aur",
    "centos",
    "clippy",
    "cmdcreate",
    "cmdcreate's",
    "debiasio",
    "dnf",
    "dominiquini",
    "dpkg",
    "favorited",
    "favoriting",
    "gedit",
    "kwrite",
    "linuxmint",
    "lvl",
    "makepkg",
    "manjaro",
    "misdetection",
    "noconfirm",
    "nvim",
    "openssl",
    "pacman",
    "paru",
    "reqwest",
    "rhel",
    "rustup",
    "upgrader",
    "uvh",
    "vscodium",
    "yay",
]
