# This file is located in ~/.config/cmdcreate/config.toml

[sys]
shell = "bash" # Your preferred shell
spoof_arch = "true" # If "true", the architecture will be spoofed to x86_64

[appearence]
favorite_indicator = "â˜…" # A symbol or string of text to indicate a favorite command