# This file is located in ~/.config/cmdcreate/config.toml

[sys]
shell = "bash" # Your preferred shell

[logs]
time_format = "%Y-%m-%d %H:%M:%S" # Formatting of time
verbose = "false" # If "true", logs will be printed to output

[appearence]
favorite_indicator = "â˜…" # A symbol or string of text to indicate a favorite command